### PR TITLE
Various improvements (check each commit separately)

### PR DESCRIPTION
**Pull request by lbmaian**
I know you're already working on another branch and already have a solution for the change YouTube endpoint, so these changes can't be merged as-is, but I think you can find use for them.

0. First commit can be ignored - it just adds basic debug logging, and I know your branch has its own more robust version.

1. https://github.com/xenova/chat-downloader/pull/50/commits/24e0d2293e5c1130fce9433b48f744376069d2ad?w=1
The HTTP library already has built-in retry and timeout functionality - they just need to be enabled.
Also ensure output file is always created even on uncaught exception.

* edit: 1.5. https://github.com/xenova/chat-downloader/pull/50/commits/dea15b357fd3611840f5e1b86c25e11dcd6a1a6e?w=1
Improve exception handling (combine try/except & try/finally, flush print), including handling HTTP RequestException.

2. https://github.com/xenova/chat-downloader/pull/50/commits/36b9f8660a85e1cb03e4cde75c578447b88b9902?w=1
Use UTF-8-BOM encoding for file output. This was only needed for MS Excel compatibility with CSV unicode files. I just applied the same encoding to the other file output types for consistency.
Also improve JSON parse error message.

3. https://github.com/xenova/chat-downloader/pull/50/commits/0203b7f5b47c52463b3cd080a8ed0ba5b95af707?w=1
Update to the new YouTube endpoint reusing param data from the `ytcfg` from the original video page. This json snippet includes these key fields: `INNERTUBE_API_VERSION`, `INNERTUBE_API_KEY`, `INNERTUBE_CONTEXT`.
This should be more robust than your solution, since it avoids the need to stub in dummy param data.
This commit also improves regex handling: more robust regex, lenient parsing, compiled regex

* edit: 3.5. https://github.com/xenova/chat-downloader/pull/50/commits/8f451c5a79b6b87a346121a224a2aa0d2f6893fd?w=1
Also added handling for chat continuation returning 404 error (in addition to the handling for 403 error).

4. https://github.com/xenova/chat-downloader/pull/50/commits/f0679f363eb9e01c8c3491a7363106162e71a7bd?w=1
Add `datetime` (ISO format that's never an offset so it's always consistent between live and replay) and `author_type` (language-agnostic enum for member, moderator, owner, etc.) fields.
Also changes the text output format to use `datetime` (rather than `time_text` or converted `timestamp`) and `author_type` (rather than `badges`). I find this more useful for my own purposes, but ideally the text output format should be configurable.

### CODE REVIEW

**Comment by xenova** [comment]
Thanks so much for the pull request! I'll definitely include some of these changes in a following update!

**Comment by lbmaian** [comment]
Great!

I messed up partitioning the commits a bit, so I fixed and force-pushed them.

**Comment by xenova** [comment]
> Great!
> 
> I messed up partitioning the commits a bit, so I fixed and force-pushed them.

No worries! Thanks again!

However, if I were to include the code on my own, you would not be credited as a "Contributor" on GitHub. If I am not mistaken, that only lists people who have contributed code via pull requests. If you would like to be included as a contributor, would you mind forking and creating a pull request with your code?

**Comment by lbmaian** [comment]
I don't mind not being listed as a contributor on github. I also currently don't have time to "rebase" the changes onto the new master atm 😦

**Comment by xenova** [comment]
> I don't mind not being listed as a contributor on github. I also currently don't have time to "rebase" the changes onto the new master atm 😦

Okay no worries! Just wanted to give credit where credit was due! 😃 Thanks again.

**Comment by lbmaian** [comment]
Don't mind me... been tinkering with my fork for my own uses, and haven't had time to "rebase" them off the massive rework on master.

**Pull request closed without merging**
