### PR TITLE
Allow using HTTP proxy servers

### PR DESCRIPTION
**Pull request by mikoim**
Goodbye, https://www.youtube.com/das_captcha 😿

### CODE REVIEW

**Comment by xenova** [comment]
This is great! Thanks for the PR 🔥 

Since the tool is also used from the command line, how can we add this as a command line argument?

According to the requests docs (https://requests.readthedocs.io/en/master/user/advanced/#proxies), proxies are specified as a dict similar to this:
``` python
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
```

So, as a command line argument, how should this be specified? [YouTube-DL](https://github.com/ytdl-org/youtube-dl) has a `--proxy` argument which seems to just take a url (as a string) and use this as the proxy.

```
--proxy URL                          Use the specified HTTP/HTTPS/SOCKS
                                     proxy. To enable SOCKS proxy, specify a
                                     proper scheme. For example
                                     socks5://127.0.0.1:1080/. Pass in an
                                     empty string (--proxy "") for direct
                                     connection
```

Should we do this or must we allow for http and https to be specified separately? (i.e. will they usually be different?)

**Comment by mikoim** [comment]
I've never seen proxies providing HTTP and HTTPS separately before. Almost streaming services use HTTPS only so we don't have to provide two options.

**Comment by xenova** [comment]
Okay sounds good 👍 Do you want to add that or should I?

**Comment by mikoim** [comment]
I'll try that.

**Comment by xenova** [comment]
Great! Thanks. I will check your changes, test, add methods from YouTube-dl's implementation and finally merge.

**Comment by xenova** [comment]
Okay I have simplified how the proxy can be specified (i.e. as a string). For the most part, I adapted YouTube-dl's implementation. I have tested it with http, https and socks5 proxies and all seem to work.

I have also added basic unit testing for these initialisation parameters (including empty proxies). However, due to security reasons, I have not included any actual test cases. For example, we could get a proxy from a free proxy list, but this could pose some security concerns (especially when specifying cookies). Most free proxies do not use https and will most likely be insecure. I most definitely do not want to be responsible for possibly revealing user's IP addresses. Proxy-usage should be the responsibility of the user. If you have any thoughts, let me know :)

If you can check my changes and perhaps do some testing on your end, I can merge it into the master branch.

**Comment by mikoim** [comment]
It works! Thank you for your improvement.

**Pull request merged**
