### PR TITLE
collect emoji id/url

### PR DESCRIPTION
**Pull request by 9001**
Hey there! Thanks for keeping up with youtube's changes and congrats on getting it packaged and stuff o/

Ran into a usecase where having all the emoji IDs and URLs would be good, so these changes modify the json `message` key to be a dict of `text` and `emoji` like so:
```patch
@@ -32521,3 +34634,5 @@
         "action_type": "add_chat_item",
-        "message": "\ud83d\ude3a",
+        "message": {
+            "text": "\ud83d\ude3a"
+        },
         "message_id": "CjsKGkNJVEhfWldvek[...]E5Xb0pMQS0zMQ%3D%3D",
@@ -32548,3 +34663,9 @@
         "action_type": "add_chat_item",
-        "message": ":_arsm::_arsr::_arsm::_arsr:",
+        "message": {
+            "text": ":_arsm::_arsr::_arsm::_arsr:",
+            "emoji": {
+                "UCdpUojq0KWZCN9bxXnZwz5w/pSSrXfiTD6-S_APZmoPgBg :_arsm:": "https://yt3.ggpht.com/0qcQMMGlKOtD3x4zS3OluvcghDAElHQ2sYE25T_R-lMb3zh7DacH4xkEqFOXxDTBPlQdqYaC4Q",
+                "UCdpUojq0KWZCN9bxXnZwz5w/yyOrXaqoH4ep_AOBjq7oDA :_arsr:": "https://yt3.ggpht.com/9Q3PbGhT37--fiX2KcWRJGZ25iaJiJXSWdFSnkN-3yfh-HI8AHsKrffC7NiNwD8uRA5IaGTofiA"
+            }
+        },
         "message_id": "CjoKGkNQR2VocGFvek80Q0[...]2dvZG9na0Y3QS02",
```

I don't feel too good about modifying the output format like that -- would much rather have it as a separate `emoji` key next to `message`, but could't think of a clean way to do that... Hm, maybe `_REMAPPING` could take a list of remappers/outputs for a single source key, like `'message': [('message', 'parse_runs'), ('emoji', 'parse_emoji')]`?

Another thing I really wanted to do was gather up all the URLs to deduplicate them, saving them up for a new action_type at the end, but ended up drawing a blank there too. Maybe you have some great ideas :>

Oh and the intention is to also maintain an archive of all emojis in a folder (named after their id probably), but I'm leaning towards doing that in a separate project since that's kinda out of scope for chat-downloader right?

### CODE REVIEW

**Comment by xenova** [comment]
Hey there! Thanks for making this PR - I am sure something like this will most certainly be useful.

Twitch actually also has something similar, which is currently parsed as this:
```json
{
    ...
    "emotes": "33:0-7",
    ...
    "message": "DansGame streamer small",
    "message_id": "2c66c510-7717-46e4-8047-28406c334e51",
    "message_type": "text_message",
    "timestamp": 1612916804280000,
    ...
 }
```

In this case, the characters 0-7 are replaced with emoji with id 33, where the url is `https://static-cdn.jtvnw.net/emoticons/v2/<emoji-id>/default/<light or dark>/<size>`, e.g. https://static-cdn.jtvnw.net/emoticons/v2/33/default/dark/1.0


Now, we could merge your idea with this for YouTube (and Twitch) and do something like this:
```json
{ 
    "message":  ":_arsm::_arsr::_arsm::_arsr:",
    "emojis": [
        {
            "shortcut": ":_arsm:",
            "id": "pSSrXfiTD6-S_APZmoPgBg",
            "channel": "UCdpUojq0KWZCN9bxXnZwz5w",
            "url": "https://yt3.ggpht.com/0qcQMMGlKOtD3x4zS3OluvcghDAElHQ2sYE25T_R-lMb3zh7DacH4xkEqFOXxDTBPlQdqYaC4Q"
        }
     ]
}
```
YouTube specifies different sizes of images by appending the url with keywords e.g. `=w24-h24-c-k-nd`, which returns a scaled and cropped version of it (24x24 centered). So, we could add a list of different sizes (to be similar to Twitch). We can also then change Twitch to have a similar output to this.

---

Overall, I think we should keep the "message" field as is. This should only be text. Instead, a "emoji" or "emote" field will then specify any emotes which are in the chat message. What do you think?

**Comment by 9001** [comment]
sounds great 👍 
Yeah might as well keep all the different sizes that youtube offers, and let other software do any url processing (strip the size hints), in case that should stop working at some point.
So regarding a separate emote field, I can't really see a clean way to have `parse_runs` emit two separate tags currently, unless:
* in `def remap`, check if the entry in `remapping_dict` is a list, and then run all the remapping functions within (allowing multiple parsers for one input field, so another `parse_runs` that only emits emoji)
* in `def remap`, assume that the remapping_function produces a dict, then unpack that and place each key/value into `info` rather than using `index`
Option 2 would require having the existing remap_functions modified to always produce a dict with the correct output key at the top level, so that doesn't sound very flexible -- so what do you think about option 1?

**Comment by xenova** [comment]
I actually like both of your ideas quite a bit. We could define some `Remapper` class which will allow us to specify whether this is just a value (potentially a dictionary) or if it is a dictionary that must be unpacked. It could also allow for more advanced remapping functionality in the future.

Perhaps something like this:
```python
class Remapper():
    def __init__(self, new_key=None, remap_function=None, to_unpack=False):
        if new_key is not None and to_unpack:
            # New key is specified, but must unpack. Not allowed
            raise ValueError(
                'If to_unpack is True, new_key may not be specified.')

        self.new_key = new_key

        if not (remap_function is callable or remap_function is None):
            raise ValueError('remap_function must be callable or None.')

        self.remap_function = remap_function
        self.to_unpack = to_unpack
```

and then for `remap`:

```python
    @staticmethod
    def remap(info, remapping_dict, remap_key, remap_input, keep_unknown_keys=False, replace_char_with_underscores=None):
        """
        A function used to remap items from one dictionary to another

        :param info: Output dictionary
        :param remapping_dict: Dictionary of remappings
        :param remap_key: The key of the remapping
        :param remap_input: The input sent to the remapping function
        :param keep_unknown_keys: If no remap is found, keep the data with its original key and value
        :param replace_char_with_underscores: If no remap is found, replace a character in the key with underscores
        """
        remap = remapping_dict.get(remap_key)

        if remap:  # A matching 'remapping' has been found, apply this remapping

            if isinstance(remap, Remapper):
                new_key = remap.new_key

                # Perform transformation
                if remap.remap_function:  # Has a remap function
                    new_value = remap.remap_function(remap_input)
                else:  # No remap function specified, apply identity transformation
                    new_value = remap_input

                # Assign values to info
                if not remap.to_unpack:
                    info[new_key] = new_value
                elif isinstance(new_value, dict):
                    info[new_key].update(new_value)
                else:
                    raise ValueError(
                        'Unable to unpack item which is not a dictionary.')

            elif isinstance(remap, str):
                # If it is just a string, simply assign the new value to this key
                info[remap] = remap_input
            else:
                raise ValueError('Unknown remapping specified.')

        elif keep_unknown_keys:
            if replace_char_with_underscores:
                remap_key = remap_key.replace(
                    replace_char_with_underscores, '_')
            info[remap_key] = remap_input
```

**Comment by xenova** [comment]
Okay I've changed it across all files now and it seems to be working. What do you think?

**Comment by 9001** [comment]
yo what, this is awesome lol
No remarks on the changeset, looks solid -- loving how it almost didn't affect most of the functions/mappings even 💯 
And it works great too of course so nothing more to add. Glad you liked the idea and thanks again for the effort on all this :D

**Comment by xenova** [comment]
Sweet! It actually cleans things up quite a bit, so thank you for the suggestion! I am just adding support for twitch emotes/urls (as described above) and I will merge when I am done with that. 🔥

**Pull request merged**
