### PR TITLE
Ignore YouTube cookie consent page

### LINKED ISSUE #85: [BUG] YouTube cookie consent page breaks chat download process.
## Basic information
- Program version: 0.0.8
- Python version: 3.9.2
- Operating system: Windows 10 10.0.19041.867

## Describe the bug
I try to save the chat from some of my videos, but it throws an error:
chat_downloader.errors.ParsingError: Unable to parse initial video data. 

Full Traceback:
chat_downloader https://www.youtube.com/watch?v=x2ukXJM0QO0
[INFO] Site: youtube.com
Traceback (most recent call last):
  File "C:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\enc\Scripts\chat_downloader.exe\__main__.py", line 7, in <module>
  File "c:\users\user\enc\lib\site-packages\chat_downloader\cli.py", line 170, in main
    run(**args.__dict__)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\chat_downloader.py", line 273, in run
    chat = downloader.get_chat(**chat_params)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\chat_downloader.py", line 166, in get_chat
    info = self.sessions[site.__name__].get_chat(**params)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 1393, in get_chat
    return self.get_chat_by_video_id(match.group('id'), kwargs)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 1367, in get_chat_by_video_id
    initial_info = self._get_initial_video_info(video_id)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 906, in _get_initial_video_info
    raise ParsingError(
chat_downloader.errors.ParsingError: Unable to parse initial video data. 

Followed by a html-page to give cookie consent.
I suspect this is an EU issue...

### If running from the command line, provide the following:
1. The command used (including the verbose tag, `-v`):
```
chat_downloader -v https://www.youtube.com/watch?v=x2ukXJM0QO0
```
2. Output from the above command:
```
[DEBUG] Python version: 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)]
[DEBUG] Program version: 0.0.8
[DEBUG] Initialisation parameters: {'cookies': None, 'proxy': None, 'headers': None}
[INFO] Site: youtube.com
[DEBUG] Program parameters: {'url': 'https://www.youtube.com/watch?v=x2ukXJM0QO0', 'start_time': None, 'end_time': None, 'max_attempts': 15, 'retry_timeout': None, 'timeout': None, 'max_messages': None, 'logging': 'debug', 'pause_on_debug': False, 'exit_on_debug': False, 'message_groups': ['messages'], 'message_types': None, 'format': 'youtube', 'format_file': None, 'chat_type': 'live', 'message_receive_timeout': 0.1, 'buffer_size': 4096, 'inactivity_timeout': None}
[DEBUG] Starting new HTTPS connection (1): www.youtube.com:443
[DEBUG] https://www.youtube.com:443 "GET /watch?v=x2ukXJM0QO0 HTTP/1.1" 302 0
[DEBUG] Starting new HTTPS connection (1): consent.youtube.com:443
[DEBUG] https://consent.youtube.com:443 "GET /m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dx2ukXJM0QO0&gl=DE&m=0&pc=yt&uxe=23983172&hl=en&src=1 HTTP/1.1" 200 None
[DEBUG] Session closed.
Traceback (most recent call last):
  File "C:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\enc\Scripts\chat_downloader.exe\__main__.py", line 7, in <module>
  File "c:\users\user\enc\lib\site-packages\chat_downloader\cli.py", line 170, in main
    run(**args.__dict__)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\chat_downloader.py", line 273, in run
    chat = downloader.get_chat(**chat_params)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\chat_downloader.py", line 166, in get_chat
    info = self.sessions[site.__name__].get_chat(**params)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 1393, in get_chat
    return self.get_chat_by_video_id(match.group('id'), kwargs)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 1367, in get_chat_by_video_id
    initial_info = self._get_initial_video_info(video_id)
  File "c:\users\user\enc\lib\site-packages\chat_downloader\sites\youtube.py", line 906, in _get_initial_video_info
    raise ParsingError(
chat_downloader.errors.ParsingError: Unable to parse initial video data. 
```
Then the contents of the consent-page, see attachment.
## Expected behavior
Chat-downloader should give consent to the cookie, so i can retrieve the chat messages.
[ytout.txt](https://github.com/xenova/chat-downloader/files/6260319/ytout.txt)

### PR DESCRIPTION
**Pull request by turbcool**
resolve #85

### CODE REVIEW

**Comment by xenova** [comment]
Thanks so much for this 😃 

Is the "RU" in the consent required? It sounds like a country-code or something like that?

I've checked how YouTube DL handles this, and it seems to be something along the lines of your earlier commits: https://github.com/ytdl-org/youtube-dl/blob/7fb9564420d43252c8f8c453d4dc54bf3ff9f8ee/youtube_dl/extractor/youtube.py#L251-L264

To be honest, I've never had a problem with consent forms (they have never appeared for me), so if possible, could you check and see what works? Thanks!

**Comment by Felk** [comment]
I can confirm that this russian consent cookie has reliably worked for me, and I'm from germany

**Comment by xenova** [comment]
Thanks for the info 👍  I'll should be able to test this all out by using a VPN and connecting to a EU server.

Will try to get this sorted as soon as possible.

**Comment by xenova** [comment]
Okay, so I have added support for generating cookies to the latest version. However, I chose to use youtube-dl's implementation as it does not seem to rely on country-code specific consent cookies. It also sets the session cookies instead of just making single requests with this cookie value. This is needed for other parts of the chat downloader which make similar requests.

I would like to credit you for bringing this issue up. but I am unsure how to do that now since I won't be able to merge this PR into master (since it is around 50 commits behind and I am using youtube-dl's implementation).

**Comment by turbcool** [comment]
It's not a problem 😃. Good its now working.

**Pull request closed without merging**
